mkdocs.yml
site_name: Hackathon Douro & Porto - Rede de Comunicação
nav:
    - Home: index.md
    - Projeto: projeto.md
    - Simulações: simul.md
    - Resultados: resultados.md
    - Conclusões: conclusoes.md
    - About: about.md
docs/
    index.md
    projeto.
    simul.md
    resultados.md
    conclusoes.md
    about.md
    LICENSE
    images/
          GatewaysLoc.jpg
          simulCrasto.jpg
          simulGalafura.jpg
          simulInfantado.jpg
          simulGlobal.jpg
          simulSeixo.jpg
          TTNGateway01.jpg
          TTNGateway03.jpg


