mkdocs.yml
site_name: Hackathon Douro & Porto - Rede de Comunicação
nav:
    - Home: index.md
    - Projeto: projeto.md
    - Simulações: simul.md
    - Resultados: resultados.md
    - Conclusões: conclusoes.md
    - About: about.md
    LICENSE
